# DO NOT EDIT THIS FILE DIRECTLY!!
# Unless this is the copy you made in the root folder of the repo, in which case
# delete this warning, keep calm and code on...

# This needs to be changed before production!
# It's the key ensuring secure form filling.
WTF_CSRF_ENABLED = True
SECRET_KEY = 'kdovyhraldraftsiuznepamatujuasimiro'
