#!flask/bin/python

# DO NOT EDIT THIS FILE DIRECTLY!!
# Unless this is the copy you made in the root folder of the repo, in which case
# delete this warning, keep calm and code on...

from app import app
# app.run(debug=True, host='127.0.0.1', port=5010, ssl_context='adhoc')
app.run(debug=True, host='127.0.0.1', port=5010, ssl_context=('app/ssl.crt', 'app/ssl.key'))
